/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConnectFour } from "./ConnectFour";
export type { ConnectFourFactory } from "./ConnectFourFactory";
